### ISSUE TITLE
Serenity reports not generating index.html and generating reports via feature file 

### ISSUE THREAD

**Issue by Vijay2871** [serenity-bdd/serenity-cucumber-starter#89]
When ran through TestRunner index.html is not generated but feature.html and  logs are generated and failed screenshots also generated and cant access the feature tab as attached below and serenity.properties
![image](https://user-images.githubusercontent.com/54226136/187570769-e46e02df-1ef1-4208-9dce-0364cfd948b8.png)

![image](https://user-images.githubusercontent.com/54226136/187570523-eb7277a0-fb02-441d-9b08-7b3680f913e9.png)

**Comment by wakaleo** [comment]
The index.html file is only generated when you run the Serenity aggregate goal via maven, not when you run the runner l.

**Comment by Vijay2871** [comment]
> The index.html file is only generated when you run the Serenity aggregate goal via maven, not when you run the runner l.

I'm using gradle project and used gradle test in terminal to run and got error even though all test passed.
feature file generated with all resonse of api and steps.
When i tried to access the capability and features i'm getting a 404 error as attached. Getting all test passed somehow the reports are not generated graphically and cant access any other tab

![image](https://user-images.githubusercontent.com/54226136/187601846-a040f0cb-c0c8-4029-ab88-9d68ec7fa9eb.png)


![image](https://user-images.githubusercontent.com/54226136/187601341-70dab863-52b9-471b-9671-649128451517.png)


Failed to generate report for Test Summary Report - java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: kotlin.text.CharsKt.titlecase(CLjava
/util/Locale;)Ljava/lang/String;
net.serenitybdd.reports.model.TagCoverageBuilder.forTagTypes(TagCoverage.kt:55)
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: kotlin.text.CharsKt.titlecase(CLjava/util/Locale;)Ljava/lang/String;
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at net.thucydides.core.reports.html.Reporter.generateReports(Reporter.java:59)
        at net.thucydides.core.reports.html.Reporter.generateReportsFor(Reporter.java:35)
        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:221)
        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
        at net.thucydides.core.reports.UserStoryTestReporter$generateReportsForTestResultsFrom.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at net.serenitybdd.plugins.gradle.AggregateTask.aggregate(AggregateTask.groovy:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:494)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:479)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:462)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$400(ExecuteActionsTaskExecuter.java:105)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:273
)

**Comment by wakaleo** [comment]
I think that is a Gradle version error, due to it using the wrong version of Kotlin - make sure you are using a recent version of Gradle (e.g. 7.3.3) and that the Kotlin version is at least 1.5.31

**Comment by Vijay2871** [comment]
> I think that is a Gradle version error, due to it using the wrong version of Kotlin - make sure you are using a recent version of Gradle (e.g. 7.3.3) and that the Kotlin version is at least 1.5.31

I'm using Java (11) and Gradle 6.8 version , which i downgrade from 7.2

**Comment by wakaleo** [comment]
This is the version I can see working here:
```
------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18 (Oracle Corporation 18+36-2087)
OS:           Mac OS X 12.4 aarch64
```

**Comment by Vijay2871** [comment]
> This is the version I can see working here:
> 
> ```
> ------------------------------------------------------------
> Gradle 7.3.3
> ------------------------------------------------------------
> 
> Build time:   2021-12-22 12:37:54 UTC
> Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71
> 
> Kotlin:       1.5.31
> Groovy:       3.0.9
> Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
> JVM:          18 (Oracle Corporation 18+36-2087)
> OS:           Mac OS X 12.4 aarch64
> ```

Thanks latest build when i ran through testrunner index.html is generated
